## usethis namespace: start
#' @importFrom cli cli_abort
#' @importFrom cli cli_alert
#' @importFrom cli cli_alert_success
#' @importFrom cli cli_progress_done
#' @importFrom cli cli_progress_update
#' @importFrom collapse .c
#' @importFrom collapse fselect
#' @importFrom collapse fsubset
#' @importFrom collapse get_vars
#' @importFrom collapse ss
#' @importFrom dplyr arrange
#' @importFrom dplyr case_when
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr if_else
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr pull
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr rename_with
#' @importFrom dplyr row_number
#' @importFrom dplyr select
#' @importFrom dplyr slice
#' @importFrom dplyr ungroup
#' @importFrom glue glue
#' @importFrom purrr map
#' @importFrom purrr map_chr
#' @importFrom purrr map2
#' @importFrom purrr pmap
#' @importFrom Rcpp sourceCpp
#' @importFrom rlang %||%
#' @importFrom rlang enexpr
#' @importFrom rlang enexprs
#' @importFrom rlang enquos
#' @importFrom rlang expr
#' @importFrom rlang exprs
#' @importFrom rlang list2
#' @importFrom rlang quo_name
#' @importFrom rlang try_fetch
#' @importFrom tibble as_tibble
#' @importFrom tidyr drop_na
#' @importFrom vctrs vec_c
#' @importFrom vctrs vec_detect_missing
#' @importFrom vctrs vec_equal
#' @importFrom vctrs vec_rbind
#' @importFrom vctrs vec_slice
#' @useDynLib NFLSim, .registration = TRUE
## usethis namespace: end
NULL
