# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

between_cpp_parallel <- function(x, left, right) {
    .Call(`_NFLSim_between_cpp_parallel`, x, left, right)
}

slice_cpp <- function(x, i) {
    .Call(`_NFLSim_slice_cpp`, x, i)
}

