# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

between_cpp <- function(x, left, right) {
    .Call('_NFLSim_between_cpp', PACKAGE = 'NFLSim', x, left, right)
}

copy_cols_cpp <- function(df1, df2, cols) {
    .Call('_NFLSim_copy_cols_cpp', PACKAGE = 'NFLSim', df1, df2, cols)
}

slice_cpp <- function(df, logical_vector) {
    .Call('_NFLSim_slice_cpp', PACKAGE = 'NFLSim', df, logical_vector)
}

